### PR TITLE
Updated lecture-08, added lecture-12

### PR DESCRIPTION
**Pull request by anya-B**
Changed lecture-08 to point to a new image location, added lecture-12. Images for formulae in lecture-12 were not needed in the end

### CODE REVIEW

**Comment by barak** [comment]
Looks good.
Could I get you to try to resolve the merge conflicts?
They look pretty minor...
(Or let me know if your git-fu isn't up to it and I'll take a closer look)

**Comment by anya-B** [comment]
I will give it a go myself if you don't mind, I should be able to do it

**Comment by anya-B** [comment]
I think the problem was me naming the file lecture-12 when it should have been lecture-11

**Comment by anya-B** [comment]
Can you merge them now or am I missing something else? I am new-ish to git

**Pull request merged**
